version: "3.5"
name: inbox-zero-services
services:
  db:
    image: postgres
    restart: always
    container_name: inbox-zero
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "inboxzero"
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 8009:5432

  redis:
    image: redis
    ports:
      - 6380:6379
    volumes:
      - database-data:/data

volumes:
  database-data:
